
logger:
  console:
    level: DEBUG

cognite:
  host:    ${COGNITE_BASE_URL}
  project: ${COGNITE_PROJECT}

  idp-authentication:
    token-url:  ${COGNITE_TOKEN_URL}
    client-id:  ${COGNITE_CLIENT_ID}
    secret:     ${COGNITE_CLIENT_SECRET}
    scopes:
      - ${COGNITE_BASE_URL}/.default
  extraction-pipeline:
    external_id: ${COGNITE_EXTRACTION_PIPELINE}


extractor:
  state-store:
    raw:
      database: ${COGNITE_STATE_DB}
      table:    ${COGNITE_STATE_TABLE}
  subscription-batch-size: 10000
  ingest-batch-size:       100000
  poll-time:               5

extractor-pipeline:
  external_id: IndustrialCanvasInstanceSpace
  config_file_path: /Users/dev/replicator/config_examples/example_config.yaml
  dataset_external_id: ${COGNITE_DATASET_EXTERNAL_ID}
  dataset_name: ${COGNITE_DATASET_NAME}

event:
  s3-delta-lake-path-events: ${AWS_S3_BUCKET_PATH_FOR_EVENTS }


asset:
  s3_delta_lake_assets:  ${AWS_S3_BUCKET_PATH_FOR_ASSETS }

data_modeling:
#  - space: test_mock_dm
   - space: IndustrialCanvasInstanceSpace

destination:
  s3:
    bucket:  ${AWS_S3_BUCKET}
    prefix:  ${S3_PREFIX}
    region:  ${AWS_REGION}
