apiVersion: v1
kind: ConfigMap
metadata:
  name: cdf-conn-config
data:
  COGNITE_TOKEN_URL: {{ .Values.env.cognite.tokenUrl | quote }}
  COGNITE_CLIENT_ID: {{ .Values.env.cognite.clientId | quote }}
  COGNITE_TOKEN_SCOPES: {{ .Values.env.cognite.tokenScopes | quote }}
  COGNITE_CLIENT_NAME: {{ .Values.env.cognite.clientName | quote }}
  COGNITE_PROJECT: {{ .Values.env.cognite.project | quote }}
  COGNITE_BASE_URL: {{ .Values.env.cognite.baseUrl | quote }}
  COGNITE_STATE_TABLE: {{ .Values.env.cognite.stateTable | quote }}
  EXTRACTOR_DATASET_ID: {{ .Values.env.extractor.datasetId | quote }}
  COGNITE_STATE_DB: {{ .Values.env.cognite.stateDb | quote }}
  COGNITE_EXTRACTION_PIPELINE: {{ .Values.env.cognite.extractionPipeline | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.env.cognite.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.env.cognite.secretAccessKey | quote }}
  AWS_S3_BUCKET: {{ .Values.env.cognite.s3Bucket | quote }}
  AWS_REGION: {{ .Values.env.cognite.region | quote }}
  S3_PREFIX: {{ .Values.env.cognite.s3Prefix | quote }}

