name: Code Quality

on:
  pull_request:
    branches: [ main ]

jobs:
  codestyle:
    runs-on: ubuntu-latest
    environment:
      name: CI

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install uv
      run: pip install uv

    - name: Create venv
      run: uv venv

    - name: Install dependencies
      run: uv pip install -e ".[dev]"

    - name: Run pre-commit hooks
      run: uv run pre-commit run --all-files
