name: Unit tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    environment:
      name: CI

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: pip install uv

    - name: Install dependencies
      run: uv sync --frozen

    - name: Run unit tests with coverage
      run: uv run coverage run --source cdf_s3_replicator -m pytest -v tests/unit

    - name: Generate coverage report
      run: uv run coverage report --fail-under=90

    - name: Generate coverage HTML
      if: matrix.python-version == '3.11'
      run: uv run coverage html

    - name: Upload coverage reports
      if: matrix.python-version == '3.11'
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov/
