name: Unit tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    environment:
      name: CI

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install u
      run: pip install uv

    - name: install requirements
      run: uv sync --frozen

    - name: Run tests
      env:
        COGNITE_BASE_URL: ${{ vars.COGNITE_BASE_URL }}
        COGNITE_PROJECT: ${{ vars.COGNITE_PROJECT }}
        COGNITE_TOKEN_URL: ${{ vars.COGNITE_TOKEN_URL }}
        COGNITE_CLIENT_ID: ${{ vars.COGNITE_CLIENT_ID }}
        COGNITE_CLIENT_SECRET: ${{ secrets.COGNITE_CLIENT_SECRET }}
        COGNITE_CLIENT_NAME: ${{ vars.COGNITE_CLIENT_NAME }}
        COGNITE_EXTRACTION_PIPELINE: ${{ vars.COGNITE_EXTRACTION_PIPELINE }}
        COGNITE_TOKEN_SCOPES: ${{ vars.COGNITE_TOKEN_SCOPES }}
        TEST_CONFIG_PATH: tests/integration/test_config.yaml

      run: uv run coverage run --source cdf_s3_extractor -m pytest -v tests/unit
